### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by mrbuche**
I think this should work once on your branch, with the token in the GitHub secrets as `DOCKERHUB_TOKEN ` and the Docker Hub repository at `dprohe/sdynpy`.

One workflow pushes the `latest` version every time a commit hits the main branch. The other pushes both the latest and a tagged version every time a tag it created.

### CODE REVIEW

**Comment by mrbuche** [comment]
Fixed some badges too, they changed the API. Also, added a badge for Codefactor grade.

**Review by dprohe — APPROVED** [review]

**Comment by dprohe** [comment]
I think I set up the docker secret correctly, but I did it after the merge, so that might be why it all failed?

**Comment by mrbuche** [comment]
@dprohe I think that could be the case, especially if you put the secret up after the merge as well.

I'm having the same problem you are with pytest on another project. I have no idea what it is yet! Something changed that wasn't our fault. Do you know what it is?

**Comment by dprohe** [comment]
Some hints here: https://stackoverflow.com/questions/74861480/getting-error-coverage-exceptions-configerror-file-pattern-cant-include

**Comment by dprohe** [comment]
Might have to do with the lines setup.cfg

https://github.com/sandialabs/sdynpy/blob/ae304ed73111bb39ab90caa9b09b69f4c9e26176/setup.cfg#L16

**Comment by mrbuche** [comment]
I agree, thanks for finding this, I'm trying it out here:

https://github.com/sandialabs/statMechCrack/pull/2

**Comment by mrbuche** [comment]
@dprohe that was it! Thank you!

**Comment by dprohe** [comment]
Made the change and pulled in the changes and it looks like the docker workflow still died.

https://github.com/sandialabs/sdynpy/actions/runs/3752899893

It seems like it connected to the docker hub but then something else happened?

**Pull request merged**
